# configuration file for dotnet-releaser
[msbuild]
project = "EasyBackupAvalonia/EasyBackupAvalonia.csproj"
configuration = "Release"
[msbuild.properties]
PublishReadyToRun = false # Disable PublishReadyToRun
PublishTrimmed = true
PublishSingleFile = false
SelfContained = true
UseAppHost = true
[github]
user = "Deadpikle"
repo = "EasyBackup"
version_prefix = ""
branches = ["main"]
[changelog]
owners = "Deadpikle"
[nuget]
publish = false
[test]
enable = false # no tests available atm
[coverage]
enable = false
[[pack]]
publish = true
rid = ["win-arm", "win-arm64"]
kinds = []
[[pack]]
publish = false
rid = ["rhel-x64"]
kinds = []
[[pack]]
rid = ["linux-x64", "linux-arm"]
kinds = ["tar"]
[[pack]]
rid = ["linux-arm64"]
kinds = ["tar"]
[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["zip"]
[brew]
publish = false
[scoop]
publish = false